---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    role: app
  name: hello-world-app
  namespace: ""
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: hello-world-app-latest
  namespace: hello-world-app
spec:
  type: GitHub
  pathname: https://github.com/cdoan1/hello-world.git
  # secretRef:
  #   name: hello-world-github-credentials
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: hello-world-app
  namespace: hello-world-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - hello-world-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-path: k8s
    apps.open-cluster-management.io/github-branch: main
  name: hello-world-app
  namespace: hello-world-app
  labels:
    app: hello-world-app
spec:
  channel: hello-world-app/hello-world-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-hello-world-scc
  namespace: hello-world-app
placementRef:
  name: dev-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policygroup-hello-world-app
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: hello-world-app
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    clusterReplicas: 1
    matchExpressions: []
    matchLabels:
      purpose: development
